name: ziko.js feature request
description: This template is for submitting a proposal to ziko.js feature request 
title: "[ziko.js]" 
labels: [ziko.js]
body:
  - type: checkboxes
    id: sub-area
    attributes:
      label: Most appropriate sub-area of ziko.js?
      description: Please select at least one.
      options:
        - label: Math
        - label: UI
        - label: Time
        - label: Data
        - label: App
        - label: Reactivity
        - label: Graphics
